version: '3'
services:
  web:
    image: todo_django
    build: .
    container_name: todo_django_container
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/db
      - app_data:/app
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000


volumes:
  db_data:
  app_data: